// 
// Decompiled by Procyon v0.5.30
// 

package org.bukkit.craftbukkit.v1_5_R3;

import org.apache.commons.lang.Validate;
import org.bukkit.Sound;

public class CraftSound
{
    private static final String[] sounds;
    
    public static String getSound(final Sound sound) {
        Validate.notNull(sound, "Sound cannot be null");
        return CraftSound.sounds[sound.ordinal()];
    }
    
    static {
        (sounds = new String[Sound.values().length])[Sound.AMBIENCE_CAVE.ordinal()] = "ambient.cave.cave";
        CraftSound.sounds[Sound.AMBIENCE_RAIN.ordinal()] = "ambient.weather.rain";
        CraftSound.sounds[Sound.AMBIENCE_THUNDER.ordinal()] = "ambient.weather.thunder";
        CraftSound.sounds[Sound.ANVIL_BREAK.ordinal()] = "random.anvil_break";
        CraftSound.sounds[Sound.ANVIL_LAND.ordinal()] = "random.anvil_land";
        CraftSound.sounds[Sound.ANVIL_USE.ordinal()] = "random.anvil_use";
        CraftSound.sounds[Sound.ARROW_HIT.ordinal()] = "random.bowhit";
        CraftSound.sounds[Sound.BREATH.ordinal()] = "random.breath";
        CraftSound.sounds[Sound.BURP.ordinal()] = "random.burp";
        CraftSound.sounds[Sound.CHEST_CLOSE.ordinal()] = "random.chestclosed";
        CraftSound.sounds[Sound.CHEST_OPEN.ordinal()] = "random.chestopen";
        CraftSound.sounds[Sound.CLICK.ordinal()] = "random.click";
        CraftSound.sounds[Sound.DOOR_CLOSE.ordinal()] = "random.door_close";
        CraftSound.sounds[Sound.DOOR_OPEN.ordinal()] = "random.door_open";
        CraftSound.sounds[Sound.DRINK.ordinal()] = "random.drink";
        CraftSound.sounds[Sound.EAT.ordinal()] = "random.eat";
        CraftSound.sounds[Sound.EXPLODE.ordinal()] = "random.explode";
        CraftSound.sounds[Sound.FALL_BIG.ordinal()] = "damage.fallbig";
        CraftSound.sounds[Sound.FALL_SMALL.ordinal()] = "damage.fallsmall";
        CraftSound.sounds[Sound.FIRE.ordinal()] = "fire.fire";
        CraftSound.sounds[Sound.FIRE_IGNITE.ordinal()] = "fire.ignite";
        CraftSound.sounds[Sound.FIZZ.ordinal()] = "random.fizz";
        CraftSound.sounds[Sound.FUSE.ordinal()] = "random.fuse";
        CraftSound.sounds[Sound.GLASS.ordinal()] = "random.glass";
        CraftSound.sounds[Sound.HURT.ordinal()] = "random.classic_hurt";
        CraftSound.sounds[Sound.HURT_FLESH.ordinal()] = "damage.hit";
        CraftSound.sounds[Sound.ITEM_BREAK.ordinal()] = "random.break";
        CraftSound.sounds[Sound.ITEM_PICKUP.ordinal()] = "random.pop";
        CraftSound.sounds[Sound.LAVA.ordinal()] = "liquid.lava";
        CraftSound.sounds[Sound.LAVA_POP.ordinal()] = "liquid.lavapop";
        CraftSound.sounds[Sound.LEVEL_UP.ordinal()] = "random.levelup";
        CraftSound.sounds[Sound.MINECART_BASE.ordinal()] = "minecart.base";
        CraftSound.sounds[Sound.MINECART_INSIDE.ordinal()] = "minecart.inside";
        CraftSound.sounds[Sound.NOTE_BASS.ordinal()] = "note.bass";
        CraftSound.sounds[Sound.NOTE_PIANO.ordinal()] = "note.harp";
        CraftSound.sounds[Sound.NOTE_BASS_DRUM.ordinal()] = "note.bd";
        CraftSound.sounds[Sound.NOTE_STICKS.ordinal()] = "note.hat";
        CraftSound.sounds[Sound.NOTE_BASS_GUITAR.ordinal()] = "note.bassattack";
        CraftSound.sounds[Sound.NOTE_SNARE_DRUM.ordinal()] = "note.snare";
        CraftSound.sounds[Sound.NOTE_PLING.ordinal()] = "note.pling";
        CraftSound.sounds[Sound.ORB_PICKUP.ordinal()] = "random.orb";
        CraftSound.sounds[Sound.PISTON_EXTEND.ordinal()] = "tile.piston.out";
        CraftSound.sounds[Sound.PISTON_RETRACT.ordinal()] = "tile.piston.in";
        CraftSound.sounds[Sound.PORTAL.ordinal()] = "portal.portal";
        CraftSound.sounds[Sound.PORTAL_TRAVEL.ordinal()] = "portal.travel";
        CraftSound.sounds[Sound.PORTAL_TRIGGER.ordinal()] = "portal.trigger";
        CraftSound.sounds[Sound.SHOOT_ARROW.ordinal()] = "random.bow";
        CraftSound.sounds[Sound.SPLASH.ordinal()] = "random.splash";
        CraftSound.sounds[Sound.SPLASH2.ordinal()] = "liquid.splash";
        CraftSound.sounds[Sound.STEP_GRASS.ordinal()] = "step.grass";
        CraftSound.sounds[Sound.STEP_GRAVEL.ordinal()] = "step.gravel";
        CraftSound.sounds[Sound.STEP_LADDER.ordinal()] = "step.ladder";
        CraftSound.sounds[Sound.STEP_SAND.ordinal()] = "step.sand";
        CraftSound.sounds[Sound.STEP_SNOW.ordinal()] = "step.snow";
        CraftSound.sounds[Sound.STEP_STONE.ordinal()] = "step.stone";
        CraftSound.sounds[Sound.STEP_WOOD.ordinal()] = "step.wood";
        CraftSound.sounds[Sound.STEP_WOOL.ordinal()] = "step.cloth";
        CraftSound.sounds[Sound.SWIM.ordinal()] = "liquid.swim";
        CraftSound.sounds[Sound.WATER.ordinal()] = "liquid.water";
        CraftSound.sounds[Sound.WOOD_CLICK.ordinal()] = "random.wood click";
        CraftSound.sounds[Sound.BAT_DEATH.ordinal()] = "mob.bat.death";
        CraftSound.sounds[Sound.BAT_HURT.ordinal()] = "mob.bat.hurt";
        CraftSound.sounds[Sound.BAT_IDLE.ordinal()] = "mob.bat.idle";
        CraftSound.sounds[Sound.BAT_LOOP.ordinal()] = "mob.bat.loop";
        CraftSound.sounds[Sound.BAT_TAKEOFF.ordinal()] = "mob.bat.takeoff";
        CraftSound.sounds[Sound.BLAZE_BREATH.ordinal()] = "mob.blaze.breathe";
        CraftSound.sounds[Sound.BLAZE_DEATH.ordinal()] = "mob.blaze.death";
        CraftSound.sounds[Sound.BLAZE_HIT.ordinal()] = "mob.blaze.hit";
        CraftSound.sounds[Sound.CAT_HISS.ordinal()] = "mob.cat.hiss";
        CraftSound.sounds[Sound.CAT_HIT.ordinal()] = "mob.cat.hitt";
        CraftSound.sounds[Sound.CAT_MEOW.ordinal()] = "mob.cat.meow";
        CraftSound.sounds[Sound.CAT_PURR.ordinal()] = "mob.cat.purr";
        CraftSound.sounds[Sound.CAT_PURREOW.ordinal()] = "mob.cat.purreow";
        CraftSound.sounds[Sound.CHICKEN_IDLE.ordinal()] = "mob.chicken.say";
        CraftSound.sounds[Sound.CHICKEN_HURT.ordinal()] = "mob.chicken.hurt";
        CraftSound.sounds[Sound.CHICKEN_EGG_POP.ordinal()] = "mob.chicken.plop";
        CraftSound.sounds[Sound.CHICKEN_WALK.ordinal()] = "mob.chicken.step";
        CraftSound.sounds[Sound.COW_IDLE.ordinal()] = "mob.cow.say";
        CraftSound.sounds[Sound.COW_HURT.ordinal()] = "mob.cow.hurt";
        CraftSound.sounds[Sound.COW_WALK.ordinal()] = "mob.cow.step";
        CraftSound.sounds[Sound.CREEPER_HISS.ordinal()] = "mob.creeper.say";
        CraftSound.sounds[Sound.CREEPER_DEATH.ordinal()] = "mob.creeper.death";
        CraftSound.sounds[Sound.ENDERDRAGON_DEATH.ordinal()] = "mob.enderdragon.end";
        CraftSound.sounds[Sound.ENDERDRAGON_GROWL.ordinal()] = "mob.enderdragon.growl";
        CraftSound.sounds[Sound.ENDERDRAGON_HIT.ordinal()] = "mob.enderdragon.hit";
        CraftSound.sounds[Sound.ENDERDRAGON_WINGS.ordinal()] = "mob.enderdragon.wings";
        CraftSound.sounds[Sound.ENDERMAN_DEATH.ordinal()] = "mob.endermen.death";
        CraftSound.sounds[Sound.ENDERMAN_HIT.ordinal()] = "mob.endermen.hit";
        CraftSound.sounds[Sound.ENDERMAN_IDLE.ordinal()] = "mob.endermen.idle";
        CraftSound.sounds[Sound.ENDERMAN_TELEPORT.ordinal()] = "mob.endermen.portal";
        CraftSound.sounds[Sound.ENDERMAN_SCREAM.ordinal()] = "mob.endermen.scream";
        CraftSound.sounds[Sound.ENDERMAN_STARE.ordinal()] = "mob.endermen.stare";
        CraftSound.sounds[Sound.GHAST_SCREAM.ordinal()] = "mob.ghast.scream";
        CraftSound.sounds[Sound.GHAST_SCREAM2.ordinal()] = "mob.ghast.affectionate scream";
        CraftSound.sounds[Sound.GHAST_CHARGE.ordinal()] = "mob.ghast.charge";
        CraftSound.sounds[Sound.GHAST_DEATH.ordinal()] = "mob.ghast.death";
        CraftSound.sounds[Sound.GHAST_FIREBALL.ordinal()] = "mob.ghast.fireball";
        CraftSound.sounds[Sound.GHAST_MOAN.ordinal()] = "mob.ghast.moan";
        CraftSound.sounds[Sound.IRONGOLEM_DEATH.ordinal()] = "mob.irongolem.death";
        CraftSound.sounds[Sound.IRONGOLEM_HIT.ordinal()] = "mob.irongolem.hit";
        CraftSound.sounds[Sound.IRONGOLEM_THROW.ordinal()] = "mob.irongolem.throw";
        CraftSound.sounds[Sound.IRONGOLEM_WALK.ordinal()] = "mob.irongolem.walk";
        CraftSound.sounds[Sound.MAGMACUBE_WALK.ordinal()] = "mob.magmacube.small";
        CraftSound.sounds[Sound.MAGMACUBE_WALK2.ordinal()] = "mob.magmacube.big";
        CraftSound.sounds[Sound.MAGMACUBE_JUMP.ordinal()] = "mob.magmacube.jump";
        CraftSound.sounds[Sound.PIG_IDLE.ordinal()] = "mob.pig.say";
        CraftSound.sounds[Sound.PIG_DEATH.ordinal()] = "mob.pig.death";
        CraftSound.sounds[Sound.PIG_WALK.ordinal()] = "mob.pig.step";
        CraftSound.sounds[Sound.SHEEP_IDLE.ordinal()] = "mob.sheep.say";
        CraftSound.sounds[Sound.SHEEP_SHEAR.ordinal()] = "mob.sheep.shear";
        CraftSound.sounds[Sound.SHEEP_WALK.ordinal()] = "mob.sheep.step";
        CraftSound.sounds[Sound.SILVERFISH_HIT.ordinal()] = "mob.silverfish.hit";
        CraftSound.sounds[Sound.SILVERFISH_KILL.ordinal()] = "mob.silverfish.kill";
        CraftSound.sounds[Sound.SILVERFISH_IDLE.ordinal()] = "mob.silverfish.say";
        CraftSound.sounds[Sound.SILVERFISH_WALK.ordinal()] = "mob.silverfish.step";
        CraftSound.sounds[Sound.SKELETON_IDLE.ordinal()] = "mob.skeleton.say";
        CraftSound.sounds[Sound.SKELETON_DEATH.ordinal()] = "mob.skeleton.death";
        CraftSound.sounds[Sound.SKELETON_HURT.ordinal()] = "mob.skeleton.hurt";
        CraftSound.sounds[Sound.SKELETON_WALK.ordinal()] = "mob.skeleton.step";
        CraftSound.sounds[Sound.SLIME_ATTACK.ordinal()] = "mob.slime.attack";
        CraftSound.sounds[Sound.SLIME_WALK.ordinal()] = "mob.slime.small";
        CraftSound.sounds[Sound.SLIME_WALK2.ordinal()] = "mob.slime.big";
        CraftSound.sounds[Sound.SPIDER_IDLE.ordinal()] = "mob.spider.say";
        CraftSound.sounds[Sound.SPIDER_DEATH.ordinal()] = "mob.spider.death";
        CraftSound.sounds[Sound.SPIDER_WALK.ordinal()] = "mob.spider.step";
        CraftSound.sounds[Sound.WITHER_DEATH.ordinal()] = "mob.wither.death";
        CraftSound.sounds[Sound.WITHER_HURT.ordinal()] = "mob.wither.hurt";
        CraftSound.sounds[Sound.WITHER_IDLE.ordinal()] = "mob.wither.idle";
        CraftSound.sounds[Sound.WITHER_SHOOT.ordinal()] = "mob.wither.shoot";
        CraftSound.sounds[Sound.WITHER_SPAWN.ordinal()] = "mob.wither.spawn";
        CraftSound.sounds[Sound.WOLF_BARK.ordinal()] = "mob.wolf.bark";
        CraftSound.sounds[Sound.WOLF_DEATH.ordinal()] = "mob.wolf.death";
        CraftSound.sounds[Sound.WOLF_GROWL.ordinal()] = "mob.wolf.growl";
        CraftSound.sounds[Sound.WOLF_HOWL.ordinal()] = "mob.wolf.howl";
        CraftSound.sounds[Sound.WOLF_HURT.ordinal()] = "mob.wolf.hurt";
        CraftSound.sounds[Sound.WOLF_PANT.ordinal()] = "mob.wolf.panting";
        CraftSound.sounds[Sound.WOLF_SHAKE.ordinal()] = "mob.wolf.shake";
        CraftSound.sounds[Sound.WOLF_WALK.ordinal()] = "mob.wolf.step";
        CraftSound.sounds[Sound.WOLF_WHINE.ordinal()] = "mob.wolf.whine";
        CraftSound.sounds[Sound.ZOMBIE_METAL.ordinal()] = "mob.zombie.metal";
        CraftSound.sounds[Sound.ZOMBIE_WOOD.ordinal()] = "mob.zombie.wood";
        CraftSound.sounds[Sound.ZOMBIE_WOODBREAK.ordinal()] = "mob.zombie.woodbreak";
        CraftSound.sounds[Sound.ZOMBIE_IDLE.ordinal()] = "mob.zombie.say";
        CraftSound.sounds[Sound.ZOMBIE_DEATH.ordinal()] = "mob.zombie.death";
        CraftSound.sounds[Sound.ZOMBIE_HURT.ordinal()] = "mob.zombie.hurt";
        CraftSound.sounds[Sound.ZOMBIE_INFECT.ordinal()] = "mob.zombie.infect";
        CraftSound.sounds[Sound.ZOMBIE_UNFECT.ordinal()] = "mob.zombie.unfect";
        CraftSound.sounds[Sound.ZOMBIE_REMEDY.ordinal()] = "mob.zombie.remedy";
        CraftSound.sounds[Sound.ZOMBIE_PIG_IDLE.ordinal()] = "mob.zombiepig.zpig";
        CraftSound.sounds[Sound.ZOMBIE_PIG_ANGRY.ordinal()] = "mob.zombiepig.zpigangry";
        CraftSound.sounds[Sound.ZOMBIE_PIG_DEATH.ordinal()] = "mob.zombiepig.zpigdeath";
        CraftSound.sounds[Sound.ZOMBIE_PIG_HURT.ordinal()] = "mob.zombiepig.zpighurt";
        CraftSound.sounds[Sound.DIG_WOOL.ordinal()] = "dig.cloth";
        CraftSound.sounds[Sound.DIG_GRASS.ordinal()] = "dig.grass";
        CraftSound.sounds[Sound.DIG_GRAVEL.ordinal()] = "dig.gravel";
        CraftSound.sounds[Sound.DIG_SAND.ordinal()] = "dig.sand";
        CraftSound.sounds[Sound.DIG_SNOW.ordinal()] = "dig.snow";
        CraftSound.sounds[Sound.DIG_STONE.ordinal()] = "dig.stone";
        CraftSound.sounds[Sound.DIG_WOOD.ordinal()] = "dig.wood";
    }
}
