name: ESPOOcore
main: me.espoo.main.main
version: 2.0
softdepend: [Vault, RPG Items, LogBlock, RpgExpSystem, NoteBlockAPI, DKLib, ProtocolLib]
author: shinkhan

commands:
  쓰레기통:
    description: 쓰레기통을 오픈합니다.
  ec:
    description: ESPOO core 플긴의 모든 명령어를 봅니다.
  o:
    description: fsafasf
  채팅청소:
    description: 모든 플레이어의 채팅을 청소합니다.
  수표:
    description: 수표를 발행합니다.
  cc:
    description: 모든 플레이어의 채팅을 청소합니다.
  지급:
    description: 모든 플레이어에게 손에든 아이템을 줍니다.
  농사보조:
    description: FarmAssist 기능을 설정합니다.
  정지:
    description: 모든 플레이어를 정지시킵니다.
  블럭:
    description: 블럭을 부수지 못하게 합니다.
  무적:
    description: 플레이어간에 PK를 금합니다.
  채팅:
    description: 채팅을 치지 못하게 합니다.
  만렙:
    description: 만렙을 설정합니다.
  인첸트목록:
    description: 인첸트 목록을 봅니다.
  인첸트:
    description: 인첸트를 합니다.
  표지판:
    description: 표지판 문구를 수정합니다.
  몬스터:
    description: 몬스터의 킬, 스폰 제한을 설정하는 도움말을 봅니다.
    aliases: [ptml]
  램:
    description: 램 통계를 확인합니다.
  tppod:
    description: x, y, z 좌표로 이동시킵니다.
  f:
    description: 텔레포트 명령어 입니다.
  PInfo:
    description: 정보를 봅니다.
  PlayerInfo:
    description: 정보를 봅니다.
  정보:
    description: 정보를 봅니다.
  ItemTimer:
    description: 아이템 타이머 도움말을 봅니다.
  Permit:
    description: 펄미션 존재, 비존재 여부를 봅니다.
  아이템금지: 
    description: 아이템 금지 기능을 활성화 합니다.
  조합방지: 
    description: 조합방지를 설정합니다.
  save: 
    description: 서버를 저장합니다.
  cmute: 
    description: 뮤트합니다.
