MobHealth:
  Pig: -1
  Cow: -1
  Spider: 30
  CaveSpider: 35
  Zombie: 30
  Skeleton: 30
  Creeper: 30
  Ocelot: -1
  Bat: -1
  Chicken: -1
  Mooshroom: -1
  Sheep: -1
  Squid: -1
  Villager: -1
  Enderman: 15
  Wolf: -1
  ZombiePigman: 40
  Blaze: 45
  Ghast: 40
  MagmaCube: -1
  Silverfish: -1
  Slime: -1
  Witch: -1
  WitherSkeleton: 60
  ZombieVillager: -1
  IronGolem: -1
  SnowGolem: -1
  EnderDragon: 1000
MobDamage:
  Pig: -1
  Cow: -1
  Spider: 8
  CaveSpider: 8
  Zombie: 8
  Skeleton: 8
  Creeper: -1
  Ocelot: -1
  Bat: -1
  Chicken: -1
  Mooshroom: -1
  Sheep: -1
  Squid: -1
  Villager: -1
  Enderman: 10
  Wolf: -1
  ZombiePigman: -1
  Blaze: 14
  Ghast: -1
  MagmaCube: -1
  Silverfish: -1
  Slime: 12
  Witch: -1
  WitherSkeleton: 15
  ZombieVillager: -1
  IronGolem: -1
  SnowGolem: -1
  EnderDragon: 50