# 친구가 말하는 채팅을 보여주게 합니다. 차단 기능을 활성화 / 비활성화 시킵니다.
Chat: true
# 친구 초대 시간 딜레이를 설정합니다.
Timer: 60
# 머리를 클릭하면 실행되는 부분입니다. 
# @p = 클릭한 플레이어
# @t = 클릭당한 플레이어
Commands:
  Left Click: 
    Command: getpos @t
    Description: 친구의 위치를 확인합니다.
  Right Click: 
    Command: tpa @t
    Description: 친구에게 tpa 신청을 합니다.
  Shift Click: 
    Command: 친구 삭제 @t
    Description: 친구를 삭제합니다.