# 설정 알아서하세요 ><

시작후 초반 무적: false
초반 무적 시간(분 단위): 10
일부 능력 금지 시간(분 단위, 0은 사용 안함): 10
기본 무장 제공: true
S랭크 능력 사용: true
시작시 리스폰으로 이동: false
사망시 자동으로 킥: true
사망시 자동으로 밴(킥이 활성화 되어야 가능): true
몬스터의 공격력 반감: true
난이도 자동으로 Easy로 설정: true
레벨 지급: true
책장 지급: false
레벨 설정: 222
나무 지급: false
배고픔 무한 모드(관련 능력은 알아서 상향됨): true
죽을 경우 죽인 사람을 보여줌: true
일정시간마다 좌표 표시: true
동물 비활성화: false
퀵 스타트 모드: true
시작시 능력 추첨 안함: false
시작시 인벤토리 초기화 안함: false
시작후 팁 출력함: true
서버 오토 세이브: false
인벤토리 세이브: false
능력 중복 가능: false
내구도 무한: true
극한모드: false
스페셜능력모드: false
신등급활성화: true