# CroZombies 플러그인 설정 파일입니다.
# 각 속성을 원하는 게임에 따라 세팅하세요.
# true와 false 철자 주의할것. 띄어쓰기도 틀려선 안됨.

백신 사용: true
영웅 사용: true
남은 체력 표시: true
게임 플레이 시간(분): 5
시작 대기시간(초): 5
숙주(명): 1
총알 장전 사용: true
권총 탄창 지급(개): 20
스나이퍼 탄창 지급(개): 5
죽인사람 출력: true
좌표 출력 사용: false
좌표 출력 시간(분): 5

생존자 좀비 킬시 아이템 지급 사용: false
아이템 코드: 265
지급 개수: 1
좀비 좀비 킬시 아이템 지급 사용: false
아이템 코드: 265
지급 개수: 1

스나이퍼 설정 변경: 아래를 설정
스나이퍼 코드: 286
스나이퍼 총알(발): 10
스나이퍼 탄창 코드: 266
스나이퍼 장전 딜레이: 2000
스나이퍼 발사 딜레이: 700
생존자 스나이퍼 데미지: 6
영웅 스나이퍼 데미지: 10

권총설정 변경: 아래를 설정
권총 코드: 293
권총 총알(발): 30
권총 탄창 코드: 265
권총 장전 딜레이: 1000
권총 발사 딜레이: 100
권총 발사 딜레이2: 150
생존자 권총 데미지: 2
영웅 권총 데미지: 3