옵션:
    #트리거에서 사용할 도구번호(숫자)
    도구: 369
    #자동저장시간(숫자)
    자동저장: 300
    #명령어썻을때 로그남기기(true/false)
    덮어쓰기로그: true
    #에러발생시 로그남기기(true/false)
    에러로그: true
    #while 제한 횟수(숫자)
    while제한횟수: 100
    #트리거 설정된 블럭 보호(true/false)
    블럭보호: true