# +--------------------------------------+
#  ChangeBackItem
#  config.yml
# +--------------------------------------+
# Disable_Worlds:
#   - <disabled_world>
#   - <...>
# +--------------------------------------+
# Remarks
# -------
# +--------------------------------------+

