name: ArmorControl
main: Main.Main
version: 1.0
description: Don't Touch Your Armor!!!
commands:
  투구:
    description: 투구를 벗을 수 없게 하거나, 벗을 수 있게 합니다.
  갑옷:
    description: 갑옷을 벗을 수 없게 하거나, 벗을 수 있게 합니다.
  바지:
    description: 바지를 벗을 수 없게 하거나, 벗을 수 있게 합니다.
  부츠:
    description: 부츠를 벗을 수 없게 하거나, 벗을 수 있게 합니다.